export const PLAY_TOGGLE = 'PLAY_TOGGLE';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';

export const FETCH_TRACK_EXECUTED = 'FETCH_TRACK_EXECUTED';

export const FETCH_PLAYLIST_BEGIN = 'FETCH_PLAYLIST_BEGIN';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const FETCH_PLAYLIST_FAILURE = 'FETCH_PLAYLIST_FAILURE';
