export const PLAY_TOGGLE = 'PLAY_TOGGLE';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';

export const REPEAT_TOGGLE = 'REPEAT_TOGGLE';
export const SHUFFLE_PLAYLIST_TOGGLE = 'SHUFFLE_PLAYLIST_TOGGLE';

export const SET_VOLUME = 'SET_VOLUME';
export const MUTE_TOGGLE = 'MUTE_TOGGLE';

export const FETCH_TRACK_EXECUTED = 'FETCH_TRACK_EXECUTED';

export const FETCH_PLAYLIST_BEGIN = 'FETCH_PLAYLIST_BEGIN';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const FETCH_PLAYLIST_FAILURE = 'FETCH_PLAYLIST_FAILURE';
